export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const INCREASE_INDEX = 'INCREASE_INDEX_CAROUSEL';
export const REDUCTION_INDEX = 'REDUCTION_INDEX_CAROUSEL';
export const INCREASE_TRENDINGINDEX = 'INCREASE_INDEX_TRENDINGCAROUSEL';
export const REDUCTION_ITRENDINGINDEX = 'REDUCTION_INDEX_TRENDINGCAROUSEL';
export const FETCH_TRENDING_PRODUCTS = 'FETCH_TRENDING_PRODUCTS';

export const LIST_PHONE_TRENDING = 'LIST_PHONE_TRENDING';
export const LIST_LAPTOP_TRENDING = 'LIST_LAPTOP_TRENDING';
